version: '3.8'

services:
  hycan:
    image: hycan:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hycan-container
    ports:
      - "80:80"
    environment:
      ENV_VAR_NAME: "value"
    volumes:
      - hycan-volume:/app/data

volumes:
  hycan-volume:
