
version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana-dashboard.json:/var/lib/grafana/dashboards/default.json
