# These are supported funding model platforms

Talking2Minds 
A former UK Special Forces soldier from Merseyside, who founded his own mental health charity after suffering post traumatic stress disorder, will be honoured by the Deputy Prime Minister tonight for his outstanding work to help, support and care for people with mental health conditions.
https://www.talking2minds.co.uk/blank-4
