site_name: HyCAN Documentation
repo_url: https://github.com/rfc391/HyCAN
nav:
  - Home: index.md
  - User Guide: user_guide.md
  - FAQ: faq.md
theme:
  name: material
plugins:
  - search
  - mkdocs-material-extensions
