
site_name: HyCAN Documentation
nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - API Reference:
      - Data Processing: api/data_processing.md
      - Visualizations: api/visualizations.md
      - API Integration: api/api_integration.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material

plugins:
  - search
